export const CREATE_AUDIO_CTX = 'CREATE_AUDIO_CTX';
export const CREATE_ANALYSER = 'CREATE_ANALYSER';
export const CREATE_MODULATOR = 'CREATE_MODULATOR';
export const CREATE_CARRIER = 'CREATE_CARRIER';
export const CREATE_GAIN = 'CREATE_GAIN';
